### ISSUE TITLE
Support StreamDeck Multi Actions

### ISSUE THREAD

**Issue by tknickman** [smitmartijn/streamdeck-zoom-plugin#4]
# Description
Awesome plugin! I have a bunch of workflows setup for my zoom calls and would love to be able to use this plugin as a step in a StreamDeck multi action. For some reason the plugin is hidden when in the add action pane of a multi action. I have never developed for a streamdeck before so I'm not sure what the issue could be, but I included repro steps and a demo below. 

Thanks again!

## Steps to reproduce
1. Open Stream Deck
2. Add a Multi Action: Stream Deck > Multi Action
3. Notice the zoom plugin disappears when in the add action pane

## Demo
![demo](https://dl.dropboxusercontent.com/s/b2tnkskl62wx99f/2020-07-08%2014.16.05.gif)

**Comment by smitmartijn** [comment]
Resolved by https://github.com/smitmartijn/streamdeck-zoom-plugin/commit/5207ce529766b4c84b187420d4777ea1321468d9

**Comment by tknickman** [comment]
Awesome, thanks!

**Comment by erikreagan** [comment]
@smitmartijn I see that the commit updated some settings in the code, but was it recompiled? I have the plugin downloaded from the master branch but still can't add actions in multistep actions.

**Comment by smitmartijn** [comment]
No, it was not. I'm waiting to finish the Windows support before releasing a new version.
